### ISSUE TITLE
Assets don't show up when installing with cocoapods 0.36.0.beta.1 (modules)

### ISSUE THREAD

**Issue by ldiqual** [TransitApp/SVProgressHUD#396] opened 2015-01-13 07:40 UTC
Images don't show after installing SVProgressHUD 1.1.2 (or `:head`) via cocoapods 0.36.0.beta.1.

![image](https://cloud.githubusercontent.com/assets/941453/5717344/ea6844b6-9ab3-11e4-8081-4a4d726f3a6a.png)

Code that shows the HUD:

```
SVProgressHUD.showSuccessWithStatus("XXXX canceled")
```

Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'SVProgressHUD', '1.1.2'
```

Cocoapods version:
```
$ pod --version
0.36.0.beta.1
```

No warnings are shown during compilation.

**Comment by ldiqual** [comment] 2015-01-13 07:50
I believe the relevant breaking change is here: https://github.com/CocoaPods/CocoaPods/issues/2730

**Comment by honkmaster** [comment] 2015-01-13 08:12
So this is not a bug of `SVProgressHUD`? Would do we have to do? Is there an official documentation?

**Comment by ldiqual** [comment] 2015-01-14 02:15
I would not consider it a bug per se, but rather a lack of support of newer generations of cocoapods. I believe every reference to `[UIImage imageNamed:]` would have to be replaced so the image is loaded from the `SVProgressHUD` bundle instead of the default bundle.

> By now, pod authors had to refer the main bundle to access their provided resources. It depends though on how they accessed the main bundle. If they referenced provided resources relatively, they could have used either `[NSBundle mainBundle]`, which will break if the framework provides the resources or they use the `bundleForClass:`, which should work with frameworks seamlessly. If they used a method which doesn't allow relative referencing like `[UIImage imageNamed:]`, which is for 3rd-party-libraries a to certain extente discouraged practise, but very popular. So that is going to break in most cases.

Here's the part that is problematic: https://github.com/TransitApp/SVProgressHUD/blob/5badd27a33c193090f5d68e9b49c6a48a1ffc5be/SVProgressHUD/SVProgressHUD.m#L265-L271

I assume that we'd have to replace `imageNamed:` by `imageWithContentsOfFile:` after grabbing the full path from `bundleForClass:`.

I'll give it a try this weekend if you don't want to tackle it.

**Comment by tmu** [comment] 2015-01-14 11:43
Hi, I just encountered the same issue. I can take a look on this even before the weekend.

**Comment by honkmaster** [comment] 2015-01-14 16:02
Feel free to submit a PR. They are very welcome at the moment, because i have very limited time till 23th.

**Comment by tmu** [comment] 2015-01-14 16:19
Sure, I'll submit it tomorrow. I've it working on my Swift/Framework setup, but I want to test with the old style (ObjC/Static lib)

**Comment by ldiqual** [comment] 2015-01-19 04:22
@tmu Any update on this? Should I look into it?

**Comment by tmu** [comment] 2015-01-19 09:18
I'll send you a PR, I didn't have time to test it on a static library setup, but it works in a framework setup and in a Swift app.

**Comment by tmu** [comment] 2015-01-19 09:24
Can somebody quickly test it on a static library setup? I might time later today or tomorrow to test it.

**Comment by ldiqual** [comment] 2015-01-20 01:25
Confirmed that it works with this method: https://github.com/TransitApp/SVProgressHUD#manually
Commented on code in the PR.

**Comment by honkmaster** [comment] 2015-01-31 11:16
I had to revert the PR because it crashes on iOS 7. We need a solution which works on both 7 and 8.

**Comment by Jasdev** [comment] 2015-02-16 00:03
Confirmed @tmu's change works on iOS 8, any projected timeline for the fix to be merged?

**Comment by ldiqual** [comment] 2015-02-16 00:04
Just PR'd changes to ensure backward compatibility with iOS 7. I couldn't test it there so I'd love to have someone with an actual iOS 7.0 phone to test.

**Comment by honkmaster** [comment] 2015-02-16 18:19
I also do not have a iOS7 at the moment to test. I could test simulator however. Will do so later on.

**Closed** 2015-02-26 21:33 UTC
